import { ref } from 'vue'

export const useProjectsDatabase = () => {
  const projects = ref([
    {
      id: 1,
      type: 'photo',
      filename: 'stars',
      fileExtension: '.png',
      name: 'Reaching for the Stars',
      photo: '/images/stars.png',
      description:
        'Photo of a night sky with stars and a silhouette of a person reaching for them.',
      date: '2024-10-27',
      group: 'Luna',
      technologies: ['PhotoShop', 'CameraRaw'],
      technologiesIcons: [
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg',
      ],
    },
    {
      id: 2,
      type: 'project',
      filename: 'cocio',
      fileExtension: '.proj',
      name: 'CocioSummerClash',
      photo: '/images/cocio.jpeg',
      description: 'Project CocioSummerClash is a hypothetical summer event in Esbjerg, Denmark.',
      date: '2025-04-04',
      group: 'Team Skærebært - Emilie, Mathias, Mikkel & Luna',
      technologies: [
        'PhotoShop',
        'Illustrator',
        'After Effects',
        'Premiere Pro',
        'Final Cut Pro',
        'Logic Pro',
      ],
      technologiesIcons: [
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/aftereffects/aftereffects-plain.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/premierepro/premierepro-plain.svg',
        '/icons/final_cut_pro.png',
        '/icons/logic_pro.png',
      ],
      link: 'https://www.youtube.com/watch?v=SWksdUOmnpI',
    },
    {
      id: 3,
      type: 'project',
      filename: 'treaty',
      fileExtension: '.proj',
      name: 'Global Plastic Treaty',
      photo: '/images/gpt.png',
      description: 'Exam Project on the Global Plastic Treaty.',
      date: '2025-01-15',
      group: 'Team Skærebært - Emilie, Mathias, Mikkel & Luna',
      technologies: [
        'HTML',
        'CSS',
        'JavaScript',
        'PhotoShop',
        'Illustrator',
        'Figma',
        'Final Cut Pro',
      ],
      technologiesIcons: [
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg',
        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-plain.svg',
        '/icons/final_cut_pro.png',
      ],
      link: 'https://lunadamm.github.io/plastic-webpage/',
    },
    {
      id: 4,
      type: 'project',
      filename: 'easv_com',
      fileExtension: '.proj',
      name: 'EASV Commercial',
      photo: '/images/easv.jpg',
      description: 'Commercial project for EASV.',
      date: '2024-12-01',
      group: 'Team Skærebært - Emilie, Mathias, Mikkel & Luna',
      technologies: ['Final Cut Pro'],
      technologiesIcons: ['/icons/final_cut_pro.png'],
      link: 'https://www.youtube.com/watch?v=kml0o7itwdk',
    },
    {
      id: 5,
      type: 'music',
      filename: 'job',
      fileExtension: '.mp3',
      name: "Lookin' for at Job",
      photo: '/images/job.png',
      description: 'Music created by me for a job application.',
      date: '2024-12-01',
      group: 'Luna',
      technologies: ['Logic Pro'],
      technologiesIcons: ['/icons/logic_pro.png'],
      link: 'https://youtu.be/xiOZxVNaL3I',
    },
  ])

  return {
    projects,
  }
}
