import { ref } from 'vue'

export const useProjectsDatabase = () => {
  const projects = ref([
    {
      id: 1,
      type: 'photo',
      filename: 'stars',
      fileExtension: '.png',
      name: 'Reaching for the Stars',
      photo: '/images/stars_low.jpg',
      description:
        'Photo of a night sky with stars and a silhouette of a person reaching for them. Taken in Tarm, Denmark.',
      date: '2024-10-27',
      group: 'Luna',
      technologies: ['PhotoShop', 'CameraRaw'],
      technologiesIcons: ['/icons/photoshop.svg', '/icons/photoshop.svg'],
      link: '/images/stars.png',
    },
    {
      id: 2,
      type: 'project',
      filename: 'cocio',
      fileExtension: '.proj',
      name: 'CocioSummerClash',
      photo: '/images/cocio.jpg',
      description:
        'Project CocioSummerClash is a hypothetical summer event in Esbjerg, Denmark. The event is a collaboration between Cocio and the Esbjerg kommune, aiming to promote the brand and engage with the audience through various activities and entertainment.',
      date: '2025-04-04',
      group: 'Team Skærebært - Emilie, Mathias, Mikkel & Luna',
      technologies: [
        'PhotoShop',
        'Illustrator',
        'After Effects',
        'Premiere Pro',
        'Figma',
        'Final Cut Pro',
        'Logic Pro',
      ],
      technologiesIcons: [
        '/icons/photoshop.svg',
        '/icons/illustrator.svg',
        '/icons/after_effects.svg',
        '/icons/premiere_pro.svg',
        '/icons/figma.svg',
        '/icons/final_cut_pro.png',
        '/icons/logic_pro.png',
      ],
      link: 'https://www.youtube.com/watch?v=SWksdUOmnpI',
    },
    {
      id: 3,
      type: 'project',
      filename: 'treaty',
      fileExtension: '.proj',
      name: 'Global Plastic Treaty',
      photo: '/images/gpt.jpg',
      description:
        '1st Semester Exam Project on the Global Plastic Treaty. The project focuses on the importance of the treaty and its impact on the environment and society. The project includes a website, a video, and our own hand-made illutrations.',
      date: '2025-01-15',
      group: 'Team Skærebært - Emilie, Mathias, Mikkel & Luna',
      technologies: [
        'HTML',
        'CSS',
        'JavaScript',
        'PhotoShop',
        'Illustrator',
        'InDesign',
        'Figma',
        'Final Cut Pro',
      ],
      technologiesIcons: [
        '/icons/html.svg',
        '/icons/css.svg',
        '/icons/js.svg',
        '/icons/photoshop.svg',
        '/icons/illustrator.svg',
        '/icons/indesign.svg',
        '/icons/figma.svg',
        '/icons/final_cut_pro.png',
      ],
      link: 'https://lunadamm.github.io/plastic-webpage/',
    },
    {
      id: 4,
      type: 'project',
      filename: 'easv_com',
      fileExtension: '.proj',
      name: 'EASV Commercial',
      photo: '/images/easv.jpg',
      description:
        'Commercial project for EASV, showing the school and its facilities. Music and audio was created by us in Logic Pro and edited in Final Cut Pro.',
      date: '2025-02-16',
      group: 'Team Skærebært - Emilie, Mathias, Mikkel & Luna',
      technologies: ['Final Cut Pro', 'Logic Pro'],
      technologiesIcons: ['/icons/final_cut_pro.png', '/icons/logic_pro.png'],
      link: 'https://www.youtube.com/watch?v=kml0o7itwdk',
    },
    {
      id: 5,
      type: 'music',
      filename: 'job',
      fileExtension: '.mp3',
      name: "Lookin' for at Job",
      photo: '/images/job.png',
      description:
        'Music created by me for a job application, reflecting me as a person. A comfy bossa nova jazz song :)',
      date: '2025-03-23',
      group: 'Luna',
      technologies: ['Logic Pro'],
      technologiesIcons: ['/icons/logic_pro.png'],
      link: 'https://youtu.be/xiOZxVNaL3I',
    },
    {
      id: 6,
      type: 'project',
      filename: 'folder',
      fileExtension: '.proj',
      name: 'Sjelborgdalen Folder',
      photo: '/images/folder.jpg',
      description:
        'Folder design for Sjelborgdalen, a local area in Esbjerg, Denmark. The folder is designed to be used for tourist, and includes information about the area and its history.',
      date: '2024-11-07',
      group: 'Tove, Mia & Luna',
      technologies: ['PhotoShop', 'Illustrator', 'InDesign', 'Logic Pro'],
      technologiesIcons: [
        '/icons/photoshop.svg',
        '/icons/illustrator.svg',
        '/icons/indesign.svg',
        '/icons/logic_pro.png',
      ],
      link: 'https://indd.adobe.com/view/fed85827-9f7f-4b90-8736-94520fc08523',
    },
    {
      id: 7,
      type: 'music',
      filename: 'waltz',
      fileExtension: '.mp3',
      name: 'Waltzing through the Night',
      photo: '/images/job.png',
      description: 'A cute little jazz waltz, made for fun.',
      date: '2023-06-29',
      group: 'Luna',
      technologies: ['Logic Pro'],
      technologiesIcons: ['/icons/logic_pro.png'],
      link: 'https://youtu.be/-JD4N13eiaY',
    },
    {
      id: 8,
      type: 'photo',
      filename: 'doggie',
      fileExtension: '.png',
      name: 'Doggie',
      photo: '/images/dog_center_low.jpg',
      description:
        'Photo of a dog in the center of the image, taken in Tarm, Denmark. The photo is edited to have a dreamy and soft look.',
      date: '2024-10-27',
      group: 'Luna',
      technologies: ['PhotoShop', 'CameraRaw'],
      technologiesIcons: ['/icons/photoshop.svg', '/icons/photoshop.svg'],
      link: '/images/dog_center.png',
    },
    {
      id: 9,
      type: 'photo',
      filename: 'sunset',
      fileExtension: '.png',
      name: 'The Sunset',
      photo: '/images/sunset_low.jpg',
      description: 'Photo of a sunset over some water, taken in Tarm, Denmark.',
      date: '2024-10-27',
      group: 'Luna',
      technologies: ['PhotoShop', 'CameraRaw'],
      technologiesIcons: ['/icons/photoshop.svg', '/icons/photoshop.svg'],
      link: '/images/sunset.png',
    },
    {
      id: 10,
      type: 'photo',
      filename: 'run',
      fileExtension: '.png',
      name: 'Running Dog',
      photo: '/images/running_dog_low.jpg',
      description:
        "Photo of a dog running in the grass, taken in Tarm, Denmark. The dog's name is Karla if anyone is wondering.",
      date: '2024-10-27',
      group: 'Luna',
      technologies: ['PhotoShop', 'CameraRaw'],
      technologiesIcons: ['/icons/photoshop.svg', '/icons/photoshop.svg'],
      link: '/images/running_dog.png',
    },
  ])

  return {
    projects,
  }
}
